spring:
  application:
    name: plant-care-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  datasource:
    url: jdbc:h2:mem:plantdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: fares
      password: fares

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
